### ISSUE TITLE
Selected tendril plot

### ISSUE THREAD

**Issue by Karpefors** [Karpefors/Tendril#2]
Introduce a function to plot selected tendril(s).

**Comment by stefanoborini** [comment]
Need more info.

**Comment by stefanoborini** [comment]
Ok, it is my understanding that what we need is basically to pick which tendril arms are actually plotted. We could add a selection argument to plot.tendril (or to plotbasic if it applies only to it)

**Comment by mark-edmondson-jones** [comment]
Did youhave in mind to add an optional term argument to the plot.Tendril function?  This could default to NULL in which case it would print all tendrils.  Or a term could be added to only plot one tendril.  Would there be any requirement to permit a list or vector so that multiple tendrils could be displayed on the same plot?

**Comment by mark-edmondson-jones** [comment]
I have implemented something similar for ae_timseries, but term can be NULL (plot all tendrils), a single value (one tendril only), or a vector of values (selected tendrils only).  Might be good to have the same logic here?  Please let me know if you want me to add this.

**Comment by mark-edmondson-jones** [comment]
@Karpefors : would you like this functionality adding to the basic and/or interactive plot?

**Comment by Karpefors** [comment]
I would like it to be possible for both types of plots.

**Comment by mark-edmondson-jones** [comment]
Great.  I will look at this later today.

**Comment by stefanoborini** [comment]
Closed by #54
