### ISSUE TITLE
Fix coloring scale limits

### ISSUE THREAD

**Issue by Karpefors** [Karpefors/Tendril#5]
There should be a 'limits' parameter set in the plot function so that the color scale is correct irrespective of the p-value range of what you plot. A fix could be to hard code limits into the plotting function:

scale_colour_gradientn(colours=tendrilpal, values = vals, limits = c(-3, 0))

**Comment by stefanoborini** [comment]
The current code I got from the word document already implements such hardcoded limits:

 27     limits_colorbar <- c(-3, 0)                                                           
 28     p <- ggplot(data=x$data, aes(x=x, y=y, group=Terms, color=cc.10), aspect="iso") +     
 29       scale_colour_gradientn(colours=tendrilpal, values = vals, limits = limits_colorbar) +
 30       coord_fixed(ratio=1) +                                                              

The questions are:

1. do we want to externalise this parameter (that is, make it so that we can pass it to plotbasic() as a parameter, or
2. derive it from the current data (but being a p-value I suspect that a hardcoded scale is better. We want to maintain consistency of association between value and color).

**Comment by Karpefors** [comment]
Yes, I think we should hard code it for now. Also, it would have been nice to be able to input your own color scale/palette but I think that would take to long time.

**Comment by stefanoborini** [comment]
Ref PR #10

**Comment by stefanoborini** [comment]
Fixed already technically, but refactored in PR #38.

It is unclear to me how to achieve the same with plotly.
