### ISSUE TITLE
Use FDR.tot for coloring

### ISSUE THREAD

**Issue by stefanoborini** [Karpefors/Tendril#93]
if we can use the p-value scale also for coloring = "FDR.tot" that would be great, since that is also a p-value.

**Comment by stefanoborini** [comment]
@Karpefors for this one I need a bit more context, as it's not clear at a first reading.

**Comment by Karpefors** [comment]
One of the possible coloring options ("p", "p.adj", "RR", etc) in plot is "FDR.tot". Currently it seems to be connected to a continuous color scale, but since it is an adjusted p-value it will always be between 0-1 and thus could be mapped to the log(p-value) scale that we use for the "p" and "p.adj" options.

Essentially in the plot.basic you could just add it to _if_ statement (  if(coloring %in% c("p", "p.adj", "fish")) ) and it will be solved I think.

**Comment by stefanoborini** [comment]
Got it, thanks.

**Comment by Karpefors** [comment]
This particular issue is fixed for normal plotting, but is not solved for permutation plotting. The same fix should be applied in the plot_permutation.R and plot_percentile.R.

**Comment by stefanoborini** [comment]
Damn I missed that! ... 2.0.2 then!
I'll fix it tomorrow.

**Comment by Karpefors** [comment]
Great. Then we’re ready to go, I think. Thanks!
